### ISSUE TITLE
Could The Model Segment Overlapping Instances

### ISSUE THREAD

**Issue by riven314** [PARMAGroup/UNet-Instance-Cell-Segmentation#4]
I appreciate the work so much and would like to apply it into another biomedical problem. 
But my problem involves highly overlapping instances. Could your model predict masks that are overlapping?

**Comment by lailai-12** [comment]
@riven314 Hi Riven, I'm having problem with the dataset, similar with issue 3 opened. May i know if you had that problem too? If yes may i know how did you solve it?

Starting epoch 1/30.
Traceback (most recent call last):
  File "main.py", line 175, in <module>
    dir_weights = args.weights)
  File "main.py", line 94, in setup_and_run_train
    train_loss = train_net(net, device, train_loader, optimizer, criterion, batch_size, isWCE = (loss == "WCE"))
  File "C:\Users\LaiLai\Desktop\Cell Segmentation\train_val.py", line 76, in train_net
    for batch_idx, (data, gt, weights) in enumerate(loader):
  File "C:\Users\LaiLai\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 346, in __next__
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\LaiLai\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\LaiLai\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\LaiLai\Desktop\Cell Segmentation\dataset.py", line 50, in __getitem__
    img = Image.open(id_img).convert('L')
  File "C:\Users\LaiLai\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\Image.py", line 2766, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'Datamcf-z-stacks-03212011_a03_s2_w25ceb90f1-7d10-4a7d-bd88-db3bb599b123.png'
